### ISSUE TITLE
How can the pre implemented by elgamal?

### ISSUE THREAD

**Issue by w1397800** [nucypher/nucypher-crypto-oss#1]
Hello, may you please give me some articles about elgamal implementing proxy re-encryption algorithms. I want to learn how can the proxy re-encryption implemented by elgamal. Looking forward your reply.@szotov

**Comment by vzotova** [comment]
Hello @w1397800 
Thank you for your interest in proxy re-encryption algorithms. 
I think @cygnusv can answer better than me

**Comment by cygnusv** [comment]
Hi @w1397800 !!
The first proxy re-encryption algorithm is actually very similar to ElGamal. 
I think this article can be of use to you ([link](https://pdfs.semanticscholar.org/ff26/95513e7e0f49a0a484818c19b6346e076172.pdf)).

**Comment by w1397800** [comment]
appreciate you 👍
